const p = document.createElement('p');
let text = document.createTextNode('This is generated by javascript');
p.appendChild(text);

const b = document.querySelector('body');
b.appendChild(p);

p.setAttribute("color", "blue");